apiVersion: v1
kind: Service
metadata: 
  name: svc1
  labels:
    day: two
    sample: sample1
spec:
  type: ClusterIP
  selector:
    day: two
    sample: sample1
    layer: frontend
  ports:
    - name: nginx
      port: 80
    - name: ics 
      port: 81
      targetPort: 8080
  sessionAffinity: ClientIP      

