apiVersion: v1
kind: Service
metadata: 
  name: svc2
  labels:
    day: two
    sample: sample1
spec:
  type: NodePort
  selector:
    day: two
    sample: sample1
    layer: backend
  ports:
    - name: nginx
      port: 80       
      nodePort: 30010 
