apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  labels:
    day: three  
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  local:
    path: /storage/day3/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: 
                - radha
