apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  labels:
    day: four      
    sample: dbapp
stringData:
  dbpwd: something
  anotherpwd: another
  essay.txt: |
    Hello there, this is an essay.
    This is second line.
    This is third line.
  lastpass: last     



