apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    day: three
    sample: sample2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: kutti-sc    
